sudo: required

services: docker

before_install:
  - docker-compose up --build -d
  - gem install bundler -v 1.17.3

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test